select * from customer_behavior_analysis..customers



--Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount_usd)
from customer_behavior_analysis..customers
group by gender



--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount_usd
from customer_behavior_analysis..customers
where discount_applied = 'Yes' and purchase_amount_usd >= (select avg(purchase_amount_usd) from customer_behavior_analysis..customers)



--Q3. Which are the top 5 products with the highest average review rating?
select top 5
	item_purchased, round(avg(review_rating),2) as avg_rating
from customer_behavior_analysis..customers
group by item_purchased
order by avg_rating desc




--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select avg(purchase_amount_usd) as avg_amount, shipping_type
from customer_behavior_analysis..customers
where shipping_type in ('Standard', 'Express')
group by shipping_type




--Q5. Do subscribed customers spend more? 
--Compare average spend and total revenue between subscribers and non-subscribers.
select 
	subscription_status, 
	count(customer_id) as customer, 
	avg(purchase_amount_usd) as avg_amount, 
	sum(purchase_amount_usd) as total_revenue
from customer_behavior_analysis..customers
group by subscription_status
order by total_revenue, avg_amount desc



--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select top 5
	item_purchased,
	100 * sum(case when discount_applied = 'Yes' Then 1 Else 0 end)/count(*) as discount_rate
from customer_behavior_analysis..customers
group by item_purchased
order by discount_rate desc





--Q7. Segment customers into New, Returning, and Loyal based on their total
-- number of previous purchases, and show the count of each segment. 


select distinct(previous_purchases)
from customer_behavior_analysis..customers
order by previous_purchases desc




with customer_type as(
	select customer_id, previous_purchases,
	CASE 
		when previous_purchases = 1 Then 'New'
		when previous_purchases between 2 and 15 then 'Returning'
		else 'Loyal'
		end as customer_segment
	from customer_behavior_analysis..customers
)

select
	customer_segment, count(*) as no_of_customers
from customer_type
group by customer_segment




--Q8. What are the top 3 most purchased products within each category? 

with item_count as(
	select 
		category,
		item_purchased,
		count(*) as total_orders,
		ROW_NUMBER() over (partition by category order by count(customer_id) desc) as item_rank
	from customer_behavior_analysis..customers
	group by category, item_purchased
)

select category, item_purchased, item_rank, total_orders
from item_count
where item_rank <=3





--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe

select 
	subscription_status,
	count(customer_id) as repear_buyers
from customer_behavior_analysis..customers
where previous_purchases > 5
group by subscription_status



--Q10. What is the revenue contribution of each age group? 
select 
	age_group,
	sum(purchase_amount_usd) as revenue
from customer_behavior_analysis..customers
group by age_group
order by revenue desc