-- ============================================================
--         CUSTOMER BEHAVIOR ANALYSIS — SQL QUERIES
-- ============================================================

USE customer_behavior_analysis;

SELECT *
FROM customers;


-- ============================================================
-- Q1. What is the total revenue generated by male vs. female customers?
-- ============================================================

SELECT
    gender,
    SUM(purchase_amount_usd) AS total_revenue
FROM customers
GROUP BY gender;


-- ============================================================
-- Q2. Which customers used a discount but still spent more
--     than the average purchase amount?
-- ============================================================

SELECT
    customer_id,
    purchase_amount_usd
FROM customers
WHERE
    discount_applied = 'Yes'
    AND purchase_amount_usd >= (
        SELECT AVG(purchase_amount_usd)
        FROM customers
    );


-- ============================================================
-- Q3. Which are the top 5 products with the highest average review rating?
-- ============================================================

SELECT TOP 5
    item_purchased,
    ROUND(AVG(review_rating), 2) AS avg_rating
FROM customers
GROUP BY item_purchased
ORDER BY avg_rating DESC;


-- ============================================================
-- Q4. Compare the average purchase amounts between
--     Standard and Express shipping.
-- ============================================================

SELECT
    shipping_type,
    AVG(purchase_amount_usd) AS avg_purchase_amount
FROM customers
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


-- ============================================================
-- Q5. Do subscribed customers spend more?
--     Compare average spend and total revenue between
--     subscribers and non-subscribers.
-- ============================================================

SELECT
    subscription_status,
    COUNT(customer_id)          AS total_customers,
    AVG(purchase_amount_usd)    AS avg_purchase_amount,
    SUM(purchase_amount_usd)    AS total_revenue
FROM customers
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_purchase_amount DESC;


-- ============================================================
-- Q6. Which 5 products have the highest percentage of
--     purchases with discounts applied?
-- ============================================================

SELECT TOP 5
    item_purchased,
    100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)
        / COUNT(*)                  AS discount_rate_pct
FROM customers
GROUP BY item_purchased
ORDER BY discount_rate_pct DESC;


-- ============================================================
-- Q7. Segment customers into New, Returning, and Loyal based
--     on their total number of previous purchases, and show
--     the count of each segment.
-- ============================================================

-- Preview distinct purchase counts
SELECT DISTINCT previous_purchases
FROM customers
ORDER BY previous_purchases DESC;

-- Segmentation CTE
WITH customer_segments AS (
    SELECT
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1              THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 15 THEN 'Returning'
            ELSE                                          'Loyal'
        END AS customer_segment
    FROM customers
)

SELECT
    customer_segment,
    COUNT(*) AS no_of_customers
FROM customer_segments
GROUP BY customer_segment;


-- ============================================================
-- Q8. What are the top 3 most purchased products
--     within each category?
-- ============================================================

WITH ranked_items AS (
    SELECT
        category,
        item_purchased,
        COUNT(*)                                                        AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        )                                                               AS item_rank
    FROM customers
    GROUP BY category, item_purchased
)

SELECT
    category,
    item_purchased,
    item_rank,
    total_orders
FROM ranked_items
WHERE item_rank <= 3;


-- ============================================================
-- Q9. Are repeat buyers (more than 5 previous purchases)
--     also likely to subscribe?
-- ============================================================

SELECT
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customers
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- ============================================================
-- Q10. What is the revenue contribution of each age group?
-- ============================================================

SELECT
    age_group,
    SUM(purchase_amount_usd) AS total_revenue
FROM customers
GROUP BY age_group
ORDER BY total_revenue DESC;